name: Generate Datas

on:
  # Execute every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Jobs to Update Datas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: eagrundy
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Deploy to the output branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
