name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the Snake SVG
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: <your-github-username>
          outputs: dist/snake.svg

      # Upload the Snake SVG to the repository
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          file_pattern: dist/snake.svg
